#!/usr/bin/env python

'''
cdascorer-test

Runs cdascorer-run with the test flag -t

Output found in the file "test_cdata.csv"

'''

import subprocess

subprocess.run(["cdascorer", "-f", "test_cdata.csv", "-t", "True"])
